app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jdbc
  max-bucket-size: 10
  retry-config:
    max-attempts: 3
    delay-type: fixed
    delay-time: 10s
    response-codes:
      - 502
      - 503
      - 504
      - 506
      - 507
      - 429
  bot-topic:
    name: link-update
    partitions: 2
    replicas: 1
  use-queue: false

api:
  bot:
    baseurl: http://localhost:8090
  github:
    baseurl: https://api.github.com/
  stackoverflow:
    baseurl: https://api.stackexchange.com/2.3

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    configUrl: '/api-docs/swagger-config'
    urls:
      - name: My Custom API
        url: '/api-docs'
