app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

api:
  bot:
    baseurl: http://localhost:8090

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    configUrl: '/api-docs/swagger-config'
    urls:
      - name: My Custom API
        url: '/api-docs'
