app:
  telegram-token: ${TELEGRAM_API_KEY}
  max-bucket-size: 10
  retry-config:
    max-attempts: 3
    delay-type: fixed
    delay-time: 10s
    response-codes:
      - 502
      - 503
      - 504
      - 506
      - 507
      - 429
  scrapper-topic:
    name: link-update
  use-queue: false

api:
  scrapper:
    baseurl: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "link-update-1"
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
    properties:
      spring:
        deserializer:
          value:
            delegate:
              class: org.springframework.kafka.support.serializer.JsonDeserializer
          key:
            delegate:
              class: org.apache.kafka.common.serialization.StringDeserializer
        json:
          value:
            default:
              type: edu.java.bot.controller.request.LinkUpdateRequest
          trusted:
            packages: "*"
          use:
            type:
              info:
                headers: false
    listener:
      ack-mode: manual
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    configUrl: '/api-docs/swagger-config'
    urls:
      - name: My Custom API
        url: '/api-docs'
