/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables;

import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatLink extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHAT_LINK</code>
     */
    public static final ChatLink CHAT_LINK = new ChatLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>CHAT_LINK.ID</code>.
     */
    public final TableField<Record, Long> ID =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>CHAT_LINK.CHAT_ID</code>.
     */
    public final TableField<Record, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHAT_LINK.LINK_ID</code>.
     */
    public final TableField<Record, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHAT_LINK.CREATED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(
        DSL.name("CREATED_AT"),
        SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false)
            .defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
        this,
        ""
    );

    private ChatLink(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ChatLink(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_LINK</code> table reference
     */
    public ChatLink(String alias) {
        this(DSL.name(alias), CHAT_LINK);
    }

    /**
     * Create an aliased <code>CHAT_LINK</code> table reference
     */
    public ChatLink(Name alias) {
        this(alias, CHAT_LINK);
    }

    /**
     * Create a <code>CHAT_LINK</code> table reference
     */
    public ChatLink() {
        this(DSL.name("CHAT_LINK"), null);
    }

    public <O extends Record> ChatLink(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, CHAT_LINK);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_868;
    }

    @Override
    @NotNull
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_8682);
    }

    @Override
    @NotNull
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_8, Keys.CONSTRAINT_86);
    }

    private transient Link _link;
    private transient Chat _chat;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null) {
            _link = new Link(this, Keys.CONSTRAINT_8);
        }

        return _link;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null) {
            _chat = new Chat(this, Keys.CONSTRAINT_86);
        }

        return _chat;
    }

    @Override
    @NotNull
    public ChatLink as(String alias) {
        return new ChatLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatLink as(Name alias) {
        return new ChatLink(alias, this);
    }

    @Override
    @NotNull
    public ChatLink as(Table<?> alias) {
        return new ChatLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLink rename(String name) {
        return new ChatLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLink rename(Name name) {
        return new ChatLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLink rename(Table<?> name) {
        return new ChatLink(name.getQualifiedName(), null);
    }
}
